import React,{useState} from 'react'
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { AiOutlineHome, AiOutlineSetting ,AiOutlineUser } from "react-icons/ai";
import { BiBookReader, BiBookmarkMinus } from "react-icons/bi";
import {MdContactPhone} from "react-icons/md";
import {useRouter} from 'next/router'
import Head from "next/head";

export const Drawer = () => {
    const router = useRouter()
    const [isLogin,setisLogin] = useState<boolean>(false)

  return (
      <>
      <Head>
        <title>Food</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <div className={styles.drawer}>
         {/* <h5>Bonjour John !</h5> */}
         {
              isLogin ? (
            <div className={styles.drawer_header}>
            <Image
              src="/images/user.webp"
              alt="logo"
              width="100"
              height="100"
            />
            <span className={styles.drawer_header_text}> John Doe </span>
          </div>
              )
              : (
                <div
                style={{
                  marginTop: "50px",
                }}
                ></div>
              )
         }
           
            <div className={styles.drawer_body}>
              <Link href="/" >
              <div className={router.asPath === "/" ? styles.active : styles.drawer_body_item}>
                <a className={router.asPath === "/" ? styles.drawer_link_active : styles.drawer_link}>
                <span className={router.asPath === "/" ? styles.icon_active :styles.icon}>
                <AiOutlineHome size={30} color={"#ddd5dddde"} />
                </span>
                  Accueil
                  </a>
              </div>
              </Link>
              <Link href="/menu">
              <div className={router.asPath === "/menu" ? styles.active : styles.drawer_body_item}>
                <a className={router.asPath === "/menu" ? styles.drawer_link_active : styles.drawer_link }>
                <span className={router.asPath === "/menu" ? styles.icon_active :styles.icon}>
                <BiBookReader size={30} color={"#ddd5dddde"} />
                </span>
                  Réserver une table
                  </a>
              </div>
              </Link>

              <Link href="/article">
              <div className={router.asPath === "/article" ? styles.active : styles.drawer_body_item}>
                <a className={router.asPath === "/article" ? styles.drawer_link_active : styles.drawer_link}>
                <span className={router.asPath === "/article" ? styles.icon_active :styles.icon}>
                <BiBookmarkMinus size={30} color={"#ddd5dddde"} />
                </span>
                  Blog</a>
                </div>
              </Link>
              <Link href="/about" >
              <div className={router.asPath === "/about" ? styles.active : styles.drawer_body_item}>
                 <a className={router.asPath === "/about" ? styles.drawer_link_active : styles.drawer_link} >
                 <span className={router.asPath === "/about" ? styles.icon_active : styles.icon}>
                  <MdContactPhone size={30} color={"#f0eef0dde"}  />
                 </span>
                   Nous contacter
                   </a>
                </div>
              </Link>
              {
                isLogin ? ( 
                <Link href="/profil" >
                <div className={router.asPath === "/profil" ? styles.active : styles.drawer_body_item}>
                  <a className={router.asPath === "/profil" ? styles.drawer_link_active : styles.drawer_link}>
                  <span className={router.asPath === "/profil" ? styles.icon_active :styles.icon}>
                  <AiOutlineUser size={30} color={"#ddd5dddde"} />
                  </span>
                  Mon profil
                  </a>
              </div>
              </Link>
                )
                : (
                  <Link href="/login" >
                  <div className={router.asPath === "/login" ? styles.active : styles.drawer_body_item}>
                    <a className={router.asPath === "/login" ? styles.drawer_link_active : styles.drawer_link}>
                    <span className={router.asPath === "/login" ? styles.icon_active :styles.icon}>
                    <AiOutlineUser size={30} color={"#ddd5dddde"} />
                    </span>
                    Se connecter
                    </a>
                </div>
                </Link>
                )
              }
             
          </div>
          <div className={styles.drawer_footer}> 
          <div>
           <Image src="/images/fast-delivery.png" alt="logo" width="200" height="200" />
          </div>
            <h5 
            style={{
              color: "#fff",
              fontSize: "1.5rem",
              fontWeight: "bold",
              colorScheme: "dark",
              }}
              >
              Nous vous livrons dans <br /> les plus brefs délais
            </h5>
          </div>
        </div>
        </>
  )
}

 